overblog_graphql:
    definitions:
        auto_mapping: false
        schema:
            query: Query
            resolver_maps:
                - App\GraphQL\ResolverMap
        mappings:
            auto_discover: false
            types:
                -
                    type: graphql
                    dir: "%kernel.project_dir%/config/graphql/types"
                    suffix: ~
